### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by aanchal-fatwani** [Devansh-Baghel/react-playground#1]
@Devansh-Baghel As part of HacktoberFest2023, I wish to update the ReadMe for this repository to present better information.
Please assign this issue to me if you're fine accepting this issue for the improvement of this project and HacktoberFest submission.

**Comment by Devansh-Baghel** [comment]
@aanchal-fatwani this repo is just a playground for me to learn react and it isn't part of hacktoberfest.
